### ISSUE TITLE
Allow case insensitive search

### ISSUE THREAD

**Issue by hastarin** [Nimgoble/WPFTextBoxAutoComplete#1]
It would be great if this allowed for case insensitive search.

Probably via another DependencyProperty to enable it over the default case sensitive search.

**Comment by Nimgoble** [comment]
Hey @hastarin,

Good idea.  I'll implement that.

**Comment by hastarin** [comment]
Awesome thanks.  I ended up hacking together a copy of your behavior that did case insensitive search since I'm not familiar with behaviors and couldn't figure out a neat way to do this in the time I had.

**Comment by Brains** [comment]
I have done this. Sorry, I don't have time to make a pull request so here is code lines:

Instead of

``` C#
where value.Substring(0, textLength) == tb.Text
```

I've inserted this:

``` C#
where string.Equals(value.Substring(0, textLength), tb.Text, StringComparison.CurrentCultureIgnoreCase)
```

@Nimgoble ~~Are you approve this fix?~~ No, my fix make it as default behavior, it's good only in my case.
