### ISSUE TITLE
Crashes if text isn't in TestItems

### ISSUE THREAD

**Issue by jsaugustyn** [Nimgoble/WPFTextBoxAutoComplete#15]
I'm getting an exception if the user types text that isn't contained in TestItems. Here's the exception:

System.NullReferenceException occurred
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=<Cannot evaluate the exception source>

Any ideas?

**Comment by Nimgoble** [comment]
This may be related to the issue @timothyparez put in.  I've merged his fix. #14 

Give that a try and let me know if that fixes it.
