### ISSUE TITLE
I need to use this inside the Datagrid

### ISSUE THREAD

**Issue by Gowthamnatanakumar** [Nimgoble/WPFTextBoxAutoComplete#18]
I would like to use this autocomplete inside the datagrid, but am unable to place it in celleditingtemplate, Will you suggest me the solution or else give me some sample that how to use inside a cell of a column?

**Comment by Nimgoble** [comment]
You could try using a DataGrid TemplateColumn and putting a Textbox in there.  Then attaching this behavior to that Textbox.

https://wpftutorial.net/DataGrid.html
