### ISSUE TITLE
It works only for one textbox. Other textboxes in the app that use this behaviour are ignore

### ISSUE THREAD

**Issue by valentinra** [Nimgoble/WPFTextBoxAutoComplete#19]
I have actually reproduced this in a simple test app. If it's useful I can make a PR with the test app.

**Comment by Nimgoble** [comment]
Go ahead and branch it, then add your test app.

**Comment by LuckyGeorge75** [comment]
Just as a quickfix (i have discovered no side effects but maybe there are some):

- remove the handling of _isSubscribed in OnAutoCompleteItemsSource:

`if (e.NewValue == null)
{
   tb.TextChanged -= onTextChanged;
   tb.PreviewKeyDown -= onKeyDown;
}
else
{
   //New source.  Add the callbacks
   tb.TextChanged += onTextChanged;
   tb.PreviewKeyDown += onKeyDown;
}`

**Comment by Nimgoble** [comment]
Verified and fixed.
