### ISSUE TITLE
Usage sample

### ISSUE THREAD

**Issue by alvaro777** [Nimgoble/WPFTextBoxAutoComplete#2]
Hi, 
I've been having a hard time getting this to work (I guess because I'm kind of newbie in WPF :) )
Would it be possible to have a simple WPF project showing how to make it work? 
Thank you so much!
Alvaro

**Comment by saurabh18cs** [comment]
when i am using this i am getting error on my xaml page .. object reference not set to an instrance of object. can you please help me in how to make it work and how to implement this in xaml page. thanks

**Comment by saurabh18cs** [comment]
Hello ,

I am able to get rid of error and can see textbox in my main xaml user control. Please help me in binding this to observablecollection. I cannot see any list matching my entered value. Please help

Regards
Saurabh

**Comment by Nimgoble** [comment]
@saurabh18cs ,

Have you looked at the ReadMe?  It gives an example of how to bind to a collection.  If so, could you please show me the XAML  you are using, and the code of your DataContext for that particular view?

**Comment by saurabh18cs** [comment]
Thanks for your quick reply, yes i have gone through the readme but not
able to understand it properly.
please find attach xaml and class i am using to bind datacontext.

Please change gif to zip and then extract the files. please look at XAML
file first where i am using clsAppSiteModel which is using
clsLandSafeGuarding.  I hope you will be able to understand the structure.
Please help me out. thanks

**Comment by saurabh18cs** [comment]
![binding](https://cloud.githubusercontent.com/assets/14213581/9829824/3d370f62-5948-11e5-9956-f59e6f6ff0a6.gif)

**Comment by Nimgoble** [comment]
Hey @saurabh18cs ,

You're binding to "AppSiteList", which is an ObservableCollection of clsSearchAppSite.  You need to bind to an ObservableCollection of strings.

**Comment by saurabh18cs** [comment]
Hi,

you mean i have to change ObservableCollection<clsSearchAppSite> to
ObservableCollection<string> in my every file. But as per standard of my
framework i have to use clsSearchAppSite. Can you please suggest someway to
change only clsAppSiteModel class as per your toolbox requirement.

Regards
Saurabh

**Comment by saurabh18cs** [comment]
hi,

as per your suggestion i have modify my class file like this but still
autopopulate list box is not appearing.

namespace iPLAN20.Model.LS
{
    public class clsAppSiteModel
    {
        clsLandSafeguarding objLandSafeguarding = new clsLandSafeguarding();
        private ObservableCollection<string> _collAppSiteList = new
ObservableCollection<string>();
        public ObservableCollection<string> AppSiteList
        {
            get { return _collAppSiteList; }
        }

```
    public clsAppSiteModel()
    {
        foreach (clsSearchAppSite appSiteNo in
```

objLandSafeguarding.GetAppSite())
            {
                _collAppSiteList.Add(appSiteNo.AppSiteNo);
            }
        }
    }
}

**Comment by Nimgoble** [comment]
@saurabh18cs ,

Sorry for the delayed response.  Can you send me the project again, please?  I'll see if I can figure out what is wrong with it.

**Comment by saurabh18cs** [comment]
Hi, No problem , thats ok..

i am curious to know whether your tool is autopopulate or autocomplete? i think list will not come for your tool it will just autocomplete the value, which is happening now.
If possible can you please help me in adding your class in my main solution and make it work instead of adding separate  project and compiling to dll and than refer this dll to my project, which i dont want.

please shadow some lights on this

Thanks

**Comment by saurabh18cs** [comment]
How can i add use this autobehaviour class to my existing project? when i am adding class to my existing wpf project and changing the namespace, i am getting following error Error 1 The name "AutoCompleteBehavior" does not exist in the namespace "clr-namespace:iPLAN20.ViewModel.CommonGIS". D:\URA\iPLAN2_Code\iplan2\03_CODE\iPLAN20\iPLAN20\Windows\LS\DLS\dckDetSafeDevt.xaml 32 52 iPLAN20

If i add your dll into my existing project than i can consume but i dont want separate project for this? Please help!!

Regards Saurabh
