### ISSUE TITLE
Autocomplete from current mouse position

### ISSUE THREAD

**Issue by nertilpoci** [Nimgoble/WPFTextBoxAutoComplete#20]
First very nice library compliments
I was using it and i came across scenario that might come in handy, when giving the user autosuggestion it would be nice if it would be possible to give suggestion for the current mouse position.
Example using tags:
Inside textbox you start typing: "Hello @'here you get autocomple suggestions based on a user list' the you continue typing "
Thank you

**Comment by Nimgoble** [comment]
This has been implemented in v1.0.5.  Use the "AutoCompleteIndicator" property.
