### ISSUE TITLE
Not compatible with DataGridTextColumn

### ISSUE THREAD

**Issue by douglasg14b** [Nimgoble/WPFTextBoxAutoComplete#4]
Noticed this today when I tried to use this for a DataGrid. This implementation of AutoComplete is not compatible with DataGridTextColumn. If I try and use this in a DataGridTextcolumn the method `OnAutoCompleteItemsSource` throws an exception since it couldn't cast that Column into a TextBox.

**Comment by Nimgoble** [comment]
Hey @douglasg14b 

Could you show me the XAML you're using to get this error?
