### ISSUE TITLE
How to bind strings?

### ISSUE THREAD

**Issue by ghostiq** [Nimgoble/WPFTextBoxAutoComplete#9]
I have created an extra field to a window:
`public IEnumerable<string> TestItems = new List<string>();`

And then in a constructor I inserted:
```
DataContext = this;
TestItems = new List<string>() { "john", "Mark", "Doe" };
```

but it doesn't load any suggestions. What else do I need?

**Comment by Quade369** [comment]
`autocomplete:AutoCompleteBehavior.AutoCompleteItemsSource="{Binding TestItems}"`

Did you add this to the XAML for the edit? 

This is how you connect the autocomplete to your actual text control.  Yours might not use the "autocomplete:" that's simply how I referenced the control in my XAML file.

**Comment by Nimgoble** [comment]
What @Quade369  said.
